// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/24/2025, 9:45:27 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/nymka/Desktop/projects/work_menagement_web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nymka/Desktop/projects/work_menagement_web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nymka/Desktop/projects/work_menagement_web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nymka/Desktop/projects/work_menagement_web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nymka/Desktop/projects/work_menagement_web/plugins/**/*.{js,ts,mjs}","/home/nymka/Desktop/projects/work_menagement_web/composables/**/*.{js,ts,mjs}","/home/nymka/Desktop/projects/work_menagement_web/utils/**/*.{js,ts,mjs}","/home/nymka/Desktop/projects/work_menagement_web/pages/index.vue","/home/nymka/Desktop/projects/work_menagement_web/pages/login.vue","/home/nymka/Desktop/projects/work_menagement_web/pages/tasks.vue","/home/nymka/Desktop/projects/work_menagement_web/pages/profile.vue","/home/nymka/Desktop/projects/work_menagement_web/pages/projects.vue","/home/nymka/Desktop/projects/work_menagement_web/pages/register.vue","/home/nymka/Desktop/projects/work_menagement_web/pages/auth/google/callback.vue","/home/nymka/Desktop/projects/work_menagement_web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/nymka/Desktop/projects/work_menagement_web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/nymka/Desktop/projects/work_menagement_web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;