// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/30/2025, 4:10:21 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/nymka/Desktop/projects/work_management_web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nymka/Desktop/projects/work_management_web/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nymka/Desktop/projects/work_management_web/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nymka/Desktop/projects/work_management_web/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/nymka/Desktop/projects/work_management_web/plugins/**/*.{js,ts,mjs}","/home/nymka/Desktop/projects/work_management_web/composables/**/*.{js,ts,mjs}","/home/nymka/Desktop/projects/work_management_web/utils/**/*.{js,ts,mjs}","/home/nymka/Desktop/projects/work_management_web/pages/index.vue","/home/nymka/Desktop/projects/work_management_web/pages/tasks.vue","/home/nymka/Desktop/projects/work_management_web/pages/projects.vue","/home/nymka/Desktop/projects/work_management_web/pages/login/index.vue","/home/nymka/Desktop/projects/work_management_web/pages/profile/index.vue","/home/nymka/Desktop/projects/work_management_web/pages/register/index.vue","/home/nymka/Desktop/projects/work_management_web/pages/dashboard/index.vue","/home/nymka/Desktop/projects/work_management_web/pages/auth/google/callback.vue","/home/nymka/Desktop/projects/work_management_web/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/nymka/Desktop/projects/work_management_web/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/nymka/Desktop/projects/work_management_web/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;